name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  GO_VERSION: '1.23'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Get dependencies
      run: go mod download
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Run go fmt
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          gofmt -s -d .
          exit 1
        fi
    
    - name: Build
      run: go build -v ./cmd/db-sync
    
    - name: Test PostgreSQL connection
      run: |
        ./db-sync -op sync -type postgres -dsn "postgres://postgres:postgres@localhost:5432/testdb?sslmode=disable" -file test-postgres.sql -tables "pg_stat_activity" || echo "Test completed"
    
    - name: Test MySQL connection
      run: |
        ./db-sync -op sync -type mysql -dsn "root:root@tcp(localhost:3306)/testdb?charset=utf8mb4" -file test-mysql.sql -tables "information_schema.tables" || echo "Test completed"

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        args: --timeout=5m

  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
        exclude:
          - os: windows
            arch: arm64
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Get dependencies
      run: go mod download
    
    - name: Build for ${{ matrix.os }}/${{ matrix.arch }}
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: |
        if [ "${{ matrix.os }}" = "windows" ]; then
          go build -ldflags="-s -w" -o db-sync-${{ matrix.os }}-${{ matrix.arch }}.exe ./cmd/db-sync
        else
          go build -ldflags="-s -w" -o db-sync-${{ matrix.os }}-${{ matrix.arch }} ./cmd/db-sync
        fi